apiVersion: v1
kind: Pod
metadata:
  name: etcd-test-connection
  labels:
    role: etcd-test-connection
spec:
  containers:
    - name: etcd-test-connection
      image: docker.io/nicolaka/netshoot:latest
      stdin: true
      tty: true
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: etcd-client-tls
          mountPath: /data/etcd-client-tls
  volumes:
    - name: etcd-client-tls
      secret:
        defaultMode: 420
        secretName: etcd-client-tls