apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd-restore-operator
  labels:
    name: etcd-restore-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: etcd-restore-operator
    spec:
      containers:
      - name: etcd-restore-operator
        image: us-east1-docker.pkg.dev/tks-gcr-pub/etcd-operator/etcd-operator:v0.10.2-tks
        command:
        - etcd-restore-operator
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
